version: 2
executorType: docker
containerInfo:
  - image: docker:17.03.0-ce-git
jobs:
  build:
    workDir: ~/src
    steps:
      - checkout
      - setup_docker_engine

      - type: shell
        command: |
          docker build -t smaantci/test-ci .

      - type: shell
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - type: shell
        command: |
          docker push smaantci/test-ci
      
