version: 2
executorType: docker
containerInfo:
  - image: alpine:3.4
    cmd: ["sh"]
    env:
      - SOME_VAR=root
jobs:
  build:
    steps:
      - type: shell
        shell: sh
        pwd: /
        command: echo $SOME_VAR
