version: 2
build_agent: picard:0.0.2956-f29406a
jobs:
  build:
    docker:
      - image: alpine:3.4

      - image: golang:1.8
        name: go

      - image: postgres:alpine
        environment:
          POSTGRES_DB: db
          POSTGRES_USER: root
          POSTGRES_PASSWORD:
        name: postgres

    working_directory: /circleci/src

    steps:
      - checkout

      - run:
          command: sleep 5 && psql -U root db < sql/init.sql
          container: postgres

      - run:
          command: psql -U root db -c "select * from test;"
          container: postgres

      - run:
          command: go build main.go
          container: go

      - run: ./main
