version: 2
jobs:
  build:
    parallelism: 4

    docker:
      - image: docker:17.07.0-ce

    working_directory: /

    steps:
      - setup_docker_engine:
          docker_layer_caching: true

      - run: docker version && echo && docker ps

      - run:
          command: docker run -it ubuntu:16.04 bash -c "while true; do echo `date` && sleep 1; done"
          background: true

      - run:
          command: docker run -it jmalloc/echo-server
          background: true

      - run:
          command: docker run -d postgres
          background: true

      - run: sleep 50
